#!/bin/sh
set -ex

if [ -n "$1" ]; then
  ISORT_CHECK="--check-only"
  BLACK_CHECK="--check"
  PYTEST_DEBUG=""
else
  ISORT_CHECK=""
  BLACK_CHECK=""
  PYTEST_DEBUG="-s --pdb --pdbcls=IPython.terminal.debugger:Pdb"
fi

isort --recursive $ISORT_CHECK src/ tests/ functional/
black $BLACK_CHECK src/ tests/ functional/
mypy src/xml_dataclasses/ --strict
pylint src/
# always output coverage report
if pytest tests/ --cov=xml_dataclasses --cov-report term --cov-report html --random-order $PYTEST_DEBUG; then
  coverage html
else
  coverage html
  exit 1
fi

mypy functional/container_test.py --strict
pytest functional/ --random-order $PYTEST_DEBUG
